package com.kohls.concrete_wsdl.updatesku.v1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.10
 * 2017-04-25T11:20:58.189+03:00
 * Generated source version: 3.1.10
 * 
 */
@WebService(targetNamespace = "http://www.kohls.com/Concrete_Wsdl/UpdateSKU/v1", name = "UpdateWarehouseAttributesPort")
@XmlSeeAlso({com.kohls.schemas.cdm.producttypescdm.v1.ObjectFactory.class, com.kohls.schemas.cdm.productgrouptypes.v1.ObjectFactory.class, com.kohls.schemas.productmdm.logisticsinterface.v1.ObjectFactory.class, com.tibco.schemas.urn.kohls.xml.schemas.message_header.v1_0.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface UpdateWarehouseAttributesPort {

    @WebMethod(operationName = "UpdateWarehouseAttributesOperation", action = "/PrivateBusinessServices/Interfaces/Logistics/LogisticsAttributeUpdateService.serviceagent/UpdateWarehouseAttributesPortEndpoint1/UpdateWarehouseAttributesOperation")
    @WebResult(name = "UpdateWarehouseAttributesOutput", targetNamespace = "http://www.kohls.com/schemas/ProductMDM/LogisticsInterface/V1.xsd", partName = "UpdateWarehouseAttributesOutput")
    public com.kohls.schemas.productmdm.logisticsinterface.v1.UpdateWarehouseAttributesOutputType updateWarehouseAttributesOperation(
        @WebParam(partName = "UpdateWarehouseAttributesInput", name = "UpdateWarehouseAttributesInput", targetNamespace = "http://www.kohls.com/schemas/ProductMDM/LogisticsInterface/V1.xsd")
        com.kohls.schemas.productmdm.logisticsinterface.v1.UpdateWarehouseAttributesInputType updateWarehouseAttributesInput
    ) throws UpdateWarehouseAttributesFault;
}
