
package com.kohls.concrete_wsdl.updatesku.v1;

import javax.xml.ws.WebFault;


/**
 * This class was generated by Apache CXF 3.3.1
 * 2019-03-14T12:45:59.463+02:00
 * Generated source version: 3.3.1
 */

@WebFault(name = "Fault", targetNamespace = "http://www.kohls.com/schemas/cdm/ProductTypesCDM/V1")
public class UpdateWarehouseAttributesFault extends Exception {

    private com.kohls.schemas.cdm.producttypescdm.v1.FaultType fault;

    public UpdateWarehouseAttributesFault() {
        super();
    }

    public UpdateWarehouseAttributesFault(String message) {
        super(message);
    }

    public UpdateWarehouseAttributesFault(String message, java.lang.Throwable cause) {
        super(message, cause);
    }

    public UpdateWarehouseAttributesFault(String message, com.kohls.schemas.cdm.producttypescdm.v1.FaultType fault) {
        super(message);
        this.fault = fault;
    }

    public UpdateWarehouseAttributesFault(String message, com.kohls.schemas.cdm.producttypescdm.v1.FaultType fault, java.lang.Throwable cause) {
        super(message, cause);
        this.fault = fault;
    }

    public com.kohls.schemas.cdm.producttypescdm.v1.FaultType getFaultInfo() {
        return this.fault;
    }
}
