package com.kohls.concrete_wsdl.getsku.v1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.3.1
 * 2019-03-14T12:45:57.420+02:00
 * Generated source version: 3.3.1
 *
 */
@WebService(targetNamespace = "http://www.kohls.com/Concrete_Wsdl/GetSKU/v1", name = "GetSKUPort")
@XmlSeeAlso({com.kohls.schemas.cdm.producttypescdm.v1.ObjectFactory.class, com.kohls.schemas.cdm.productgrouptypes.v1.ObjectFactory.class, com.tibco.schemas.urn.kohls.xml.schemas.message_header.v1_0.ObjectFactory.class, com.kohls.schemas.cdm.bsinputoutputtypes.v1.ObjectFactory.class, com.tibco.cim.services.adminservice.wsdl._2.ObjectFactory.class})
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
public interface GetSKUPort {

    @WebMethod(operationName = "GetSKUOperation", action = "/BusinessServices/Interfaces/SKU/GetSKUService.serviceagent/HTTPConnection/GetSKUOperation")
    @WebResult(name = "GetSKUOutput", targetNamespace = "http://www.kohls.com/schemas/cdm/BSInputOutputTypes/V1", partName = "GetSKUOutput")
    public com.kohls.schemas.cdm.bsinputoutputtypes.v1.GetSKUOutput getSKUOperation(
        @WebParam(partName = "GetSKUInput", name = "GetSKUInput", targetNamespace = "http://www.kohls.com/schemas/cdm/BSInputOutputTypes/V1")
        com.kohls.schemas.cdm.bsinputoutputtypes.v1.GetSKUInput getSKUInput
    ) throws GetSKUFault;
}
