rexmit:
    auditEnabled: true
    auditQueue: rexmit.audit
    errorQueue: rexmit.error
    mqConnectionList: localhost(61616)
    mqMngr: Dev
    mqChannel: SYSTEM.DEF.SVRCONN
    mqUser: admin
    mqPassword: MQ_REXMIT_PASSWORD_ALIAS
    
bwlog:
    enabled: true
    queue: bwlog
    mqConnectionList: localhost(61616)
    mqMngr: Dev
    mqChannel: SYSTEM.DEF.SVRCONN
    mqUser: admin
    mqPassword: MQ_REXMIT_PASSWORD_ALIAS
    severity:
        audit: 0
        debug: 50
        info: 40
        warn: 30
        error: 20
        fatal: 10
